services:
  auth_service:
    build:
      context: ./backend/auth_service
    env_file:
      - ./backend/auth_service/.env
    ports:
      - "8000:8000"
    command: ["uvicorn","auth_service.main:app","--host","0.0.0.0","--port","8000"]

  project_service:
    build:
      context: ./backend/project_service
    env_file:
      - ./backend/project_service/.env
    ports:
      - "8001:8001"
    command: ["uvicorn","project_service.main:app","--host","0.0.0.0","--port","8001"]

  hypothesis_service:
    build:
      context: ./backend/hypothesis_service
    env_file:
      - ./backend/hypothesis_service/.env
    ports:
      - "8002:8002"
    command: ["uvicorn","hypothesis_service.main:app","--host","0.0.0.0","--port","8002"]

volumes:
  db_data:
